Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -36,7 +36,10 @@ BUNDLE_BIN="$BUILD_DIR/vendor/bundle/ruby/2.2.0/bin/bundle"
 BUNDLE_GEMFILE="$BUILD_DIR/Gemfile"
 BUNDLE_CONFIG="$BUILD_DIR/.bundle/config"
 
+echo "executing bundle show"
 bundle show skim
+echo "error code was"
+echo $?
 
 # Source commands in buildpack-run.sh (i.e. the commmands in buildpack-run.sh
 # are executed in the current shell, not in a new shell as it would be the case
